import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import Alert from "@/components/common/alert";
import { ReactQueryProvider } from "./react-query-provider";
import AdminPanelLayout from "@/components/admin-panel/admin-panel-layout";
import { ContentLayout } from "@/components/admin-panel/content-layout";
import DialogModal from "@/components/common/dialog";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <ReactQueryProvider>
      <SessionProvider>
        <html lang="en">
          <body>
            {/*<SidebarProvider>
              <AppSidebar />
              <main className="flex-1">
                <SidebarTrigger />
                <div className="p-6">{children}</div>
              </main>
            </SidebarProvider>*/}
            <AdminPanelLayout>
              <ContentLayout title="test">{children}</ContentLayout>
            </AdminPanelLayout>
            <Toaster />
            <Alert />
            <DialogModal />
          </body>
        </html>
      </SessionProvider>
    </ReactQueryProvider>
  );
}

/*export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}*/
